# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install browserstack-local
- script: npm install request
- script: npm install async
- script: npm install vsts-task-lib
- script: npm install somemodule
- script: npm install xml2js
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'LocalConnection'
- script: echo Hello, world!
# - script: mvn compile
- script: mvn clean compile test -P single
- script: npm install async
  displayName: 'Run a one-line script'

- task: BrowserStackResults@0

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
